// BFS on graph generated by thompson
#include <ctype.h>
#include <stdbool.h>
#include <string.h>

#include "nfa.h"
#include "queue.h"
static int
packer(int pos, int state, int V)
{
	return pos * V + state;
}

static bool
labelMatches(const struct token *t, char c)
{
	switch (t->type) {
	case TOKEN_CHAR:
		return c == t->curr;
	case TOKEN_DIGIT:
		return isdigit((unsigned char)c);
	case TOKEN_WORD:
		return isalnum((unsigned char)c) || c == '_';
	case TOKEN_ANY:
		return true;
	case TOKEN_INCLUSION: {
		// true if c is in t->group
		int len = strlen(t->group);
		for (int i = 0; i < len; ++i) {
			if (t->group[i] == c)
				return true;
		}
		return false;
	}
	case TOKEN_EXCLUSION: {
		int len = strlen(t->group);
		for (int i = 0; i < len; ++i) {
			if (t->group[i] == c)
				return false;
		}
		return true;
	}
	default:
		return false;
	}
}

bool
handleInput(const char *input, struct NfaInfo *nfa, bool endAnchor)
{
	// first skip all epsilon closures
	int	     V = nfa->g->V, len = strlen(input);
	int	     slots = V * (len + 1);
	struct Queue q;
	int	     qarr[slots];
	bool	     vis[slots];
	for (int i = 0; i < slots; ++i)
		qarr[i] = 0, vis[i] = false;
	q.arr  = qarr;
	q.head = q.tail = 0;
	queue_push(&q, packer(0, nfa->start, V));
	while (!queue_isEmpty(&q)) {
		int id	  = queue_pop(&q);
		int state = id % V, pos = id / V;
		if (state == nfa->accept && (!endAnchor || pos == len))
			return true;
		for (struct Node *e = nfa->g->adj[state]; e; e = e->next) {
			int nid;
			if (e->label.type == TOKEN_EPSILON)
				nid = packer(pos, e->dest, V);
			else if (pos < len &&
			    labelMatches(&e->label, input[pos]))
				nid = packer(pos + 1, e->dest, V);
			else
				continue;
			if (!vis[nid])
				vis[nid] = true, queue_push(&q, nid);
		}
	}
	return false;
}
